### ISSUE TITLE
norch stopped working after "npm update"

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#70]
Symlink missing for `leveldown`? Get error message trying to start norch, install suggested package (leveldown) and get same message. Running norch-stuff globally since I'm not tinkering with that part of the search solution.
```
$ norch

/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/util.js:71
    throw new LevelUPError(missingLevelDOWNError)
          ^
LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`
    at getLevelDOWN (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/util.js:71:11)
    at LevelUP.open (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/levelup.js:113:37)
    at new LevelUP (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/levelup.js:86:8)
    at LevelUP [as level] (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/levelup.js:46:12)
    at new module.exports (/usr/local/lib/node_modules/norch/node_modules/search-index/lib/search-index.js:42:12)
    at new module.exports (/usr/local/lib/node_modules/norch/lib/norch.js:37:13)
    at module.exports (/usr/local/lib/node_modules/norch/lib/norch.js:7:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/norch/bin/norch:3:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
$ sudo npm install -g leveldown
Password:
|
> leveldown@1.0.1 install /usr/local/lib/node_modules/leveldown
> node-gyp rebuild

  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
  CXX(target) Release/obj.target/leveldown/src/batch_async.o
  CXX(target) Release/obj.target/leveldown/src/database.o
  CXX(target) Release/obj.target/leveldown/src/database_async.o
  CXX(target) Release/obj.target/leveldown/src/iterator.o
  CXX(target) Release/obj.target/leveldown/src/iterator_async.o
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
  SOLINK_MODULE(target) Release/leveldown.node
  SOLINK_MODULE(target) Release/leveldown.node: Finished
leveldown@1.0.1 /usr/local/lib/node_modules/leveldown
├── bindings@1.2.1
├── fast-future@1.0.1
├── nan@1.5.3
└── abstract-leveldown@2.0.3 (xtend@3.0.0)
$ norch

/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/util.js:71
    throw new LevelUPError(missingLevelDOWNError)
          ^
LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`
    at getLevelDOWN (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/util.js:71:11)
    at LevelUP.open (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/levelup.js:113:37)
    at new LevelUP (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/levelup.js:86:8)
    at LevelUP [as level] (/usr/local/lib/node_modules/norch/node_modules/search-index/node_modules/levelup/lib/levelup.js:46:12)
    at new module.exports (/usr/local/lib/node_modules/norch/node_modules/search-index/lib/search-index.js:42:12)
    at new module.exports (/usr/local/lib/node_modules/norch/lib/norch.js:37:13)
    at module.exports (/usr/local/lib/node_modules/norch/lib/norch.js:7:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/norch/bin/norch:3:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by fergiemcdowall** [comment]
Yes, `npm update` has weaker dependency management compared with `npm install`

http://stackoverflow.com/questions/12478679/npm-install-vs-update-whats-the-difference

Hmmm, I wonder if `npm install -g --force` is the best way to get the latest version

**Comment by eklem** [comment]
That did the trick!
