### ISSUE TITLE
Can't install norch

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#82]
Trying to install norch, but it fails. It's OSX and I have started Xcode (build-stuff) beforehand. Is this a bug within norch or something I've f***** up installing/re-installing node.js and npm?

```consol
$ npm install norch
npm WARN package.json norch-bootstrap@0.0.6 No repository field.
\
> leveldown@0.10.4 install /Users/eklem/node_modules/norch/node_modules/search-index/node_modules/leveldown
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: printf: Resource temporarily unavailable
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/eklem/node_modules/norch/node_modules/search-index/node_modules/leveldown
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "norch"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eklem/npm-debug.log
```

**Comment by eklem** [comment]
Other node-stuff is working. Get to install modules and run code.

**Comment by fergiemcdowall** [comment]
It seems to be a problem with the C-compilation in `level-down`

Can you do `npm install level-down` ?

**Comment by eklem** [comment]
No
```consol
$ npm install level-down
npm WARN package.json norch-bootstrap@0.0.6 No repository field.
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "level-down"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code E404

npm ERR! 404 Not Found: level-down
npm ERR! 404
npm ERR! 404 'level-down' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eklem/npm-debug.log
```

**Comment by fergiemcdowall** [comment]
Sorry- leveldown without the minus

`npm install leveldown`

**Comment by eklem** [comment]
Same error as when `npm install norch`

**Comment by fergiemcdowall** [comment]
Since this problem is probably unrelated to an npm package Im going to close this issue for the time being...

**Comment by eklem** [comment]
No problem!

**Comment by eklem** [comment]
Fixed. Most probably an issue with an earlier Node-installation.
